[[redirects]]
    from = "/api"
    to = "https://crates.io/api/v1"
    status = 200
    force = true
    headers = {X-From = "Netlify"}


[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
